sonar.projectKey=vamsimorla3_taskmanager-capstone
sonar.organization=vamsimorla3

sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

sonar.qualitygate.wait=true
